import {
  Youtube,
  Music2,
  Instagram,
  Twitter,
  Facebook,
  Linkedin,
  Ghost,
  Pin,
  Twitch,
  Gamepad2,
  Mail,
  Heart,
  Coffee,
  ShoppingBag,
  Podcast,
  GraduationCap,
  Users,
  Store,
  Package,
  Sparkles,
  AtSign,
  MessageCircle,
  Play,
  BookOpen,
  Send,
  type LucideIcon
} from 'lucide-react'

export interface Platform {
  id: string
  name: string
  icon: LucideIcon
  iconColor: string
  accentColor: string
  gradient: string
  description: string
  inputs: PlatformInput[]
}

export interface PlatformInput {
  id: string
  label: string
  type: 'number' | 'slider' | 'select'
  min?: number
  max?: number
  step?: number
  defaultValue: number
  tooltip?: string
}

export const platforms: Platform[] = [
  {
    id: 'youtube',
    name: 'YouTube',
    icon: Youtube,
    iconColor: 'text-red-500',
    accentColor: '#ef4444',
    gradient: 'from-red-500 to-red-700',
    description: 'Ad revenue, memberships, and sponsorships',
    inputs: [
      { id: 'subscribers', label: 'Subscribers', type: 'number', min: 0, max: 100000000, defaultValue: 10000, tooltip: 'Total channel subscribers' },
      { id: 'monthlyViews', label: 'Monthly Views', type: 'number', min: 0, max: 1000000000, defaultValue: 100000, tooltip: 'Average views per month' },
      { id: 'cpm', label: 'CPM ($)', type: 'slider', min: 1, max: 15, step: 0.5, defaultValue: 4, tooltip: 'Cost per 1000 ad impressions' },
    ],
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    icon: Music2,
    iconColor: 'text-pink-500',
    accentColor: '#ec4899',
    gradient: 'from-pink-500 to-cyan-500',
    description: 'Creator fund and brand partnerships',
    inputs: [
      { id: 'followers', label: 'Followers', type: 'number', min: 0, max: 100000000, defaultValue: 50000, tooltip: 'Total followers' },
      { id: 'monthlyViews', label: 'Monthly Views', type: 'number', min: 0, max: 1000000000, defaultValue: 500000, tooltip: 'Average views per month' },
      { id: 'engagementRate', label: 'Engagement Rate (%)', type: 'slider', min: 1, max: 20, step: 0.5, defaultValue: 6, tooltip: 'Likes + comments / views' },
    ],
  },
  {
    id: 'instagram',
    name: 'Instagram',
    icon: Instagram,
    iconColor: 'text-pink-500',
    accentColor: '#ec4899',
    gradient: 'from-purple-500 via-pink-500 to-orange-500',
    description: 'Reels, posts, and brand deals',
    inputs: [
      { id: 'followers', label: 'Followers', type: 'number', min: 0, max: 100000000, defaultValue: 25000, tooltip: 'Total followers' },
      { id: 'avgLikes', label: 'Avg Likes per Post', type: 'number', min: 0, max: 10000000, defaultValue: 1000, tooltip: 'Average likes per post' },
      { id: 'postsPerMonth', label: 'Posts per Month', type: 'slider', min: 1, max: 60, step: 1, defaultValue: 12, tooltip: 'How often you post' },
    ],
  },
  {
    id: 'twitter',
    name: 'X (Twitter)',
    icon: Twitter,
    iconColor: 'text-zinc-400',
    accentColor: '#a1a1aa',
    gradient: 'from-zinc-600 to-zinc-800',
    description: 'Creator subscriptions and ads revenue share',
    inputs: [
      { id: 'followers', label: 'Followers', type: 'number', min: 0, max: 100000000, defaultValue: 10000, tooltip: 'Total followers' },
      { id: 'impressions', label: 'Monthly Impressions', type: 'number', min: 0, max: 1000000000, defaultValue: 500000, tooltip: 'Total monthly impressions' },
      { id: 'subscribers', label: 'Paid Subscribers', type: 'number', min: 0, max: 1000000, defaultValue: 0, tooltip: 'X Premium subscribers' },
    ],
  },
  {
    id: 'facebook',
    name: 'Facebook',
    icon: Facebook,
    iconColor: 'text-blue-500',
    accentColor: '#3b82f6',
    gradient: 'from-blue-600 to-blue-800',
    description: 'In-stream ads and stars',
    inputs: [
      { id: 'followers', label: 'Followers', type: 'number', min: 0, max: 100000000, defaultValue: 50000, tooltip: 'Page followers' },
      { id: 'watchMinutes', label: 'Monthly Watch Minutes', type: 'number', min: 0, max: 100000000, defaultValue: 100000, tooltip: 'Total watch time per month' },
    ],
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    icon: Linkedin,
    iconColor: 'text-blue-400',
    accentColor: '#60a5fa',
    gradient: 'from-blue-700 to-blue-900',
    description: 'Newsletter and consulting revenue',
    inputs: [
      { id: 'followers', label: 'Followers', type: 'number', min: 0, max: 10000000, defaultValue: 5000, tooltip: 'Total followers' },
      { id: 'newsletterSubs', label: 'Newsletter Subscribers', type: 'number', min: 0, max: 1000000, defaultValue: 1000, tooltip: 'Newsletter subscribers' },
    ],
  },
  {
    id: 'snapchat',
    name: 'Snapchat',
    icon: Ghost,
    iconColor: 'text-yellow-400',
    accentColor: '#facc15',
    gradient: 'from-yellow-400 to-yellow-500',
    description: 'Spotlight and creator programs',
    inputs: [
      { id: 'followers', label: 'Followers', type: 'number', min: 0, max: 100000000, defaultValue: 10000, tooltip: 'Total followers' },
      { id: 'spotlightViews', label: 'Spotlight Views', type: 'number', min: 0, max: 100000000, defaultValue: 50000, tooltip: 'Monthly Spotlight views' },
    ],
  },
  {
    id: 'pinterest',
    name: 'Pinterest',
    icon: Pin,
    iconColor: 'text-red-500',
    accentColor: '#ef4444',
    gradient: 'from-red-600 to-red-700',
    description: 'Creator rewards and affiliate income',
    inputs: [
      { id: 'followers', label: 'Followers', type: 'number', min: 0, max: 100000000, defaultValue: 10000, tooltip: 'Total followers' },
      { id: 'monthlyViews', label: 'Monthly Views', type: 'number', min: 0, max: 1000000000, defaultValue: 100000, tooltip: 'Monthly pin views' },
      { id: 'ideaPins', label: 'Idea Pins / Month', type: 'slider', min: 1, max: 100, step: 1, defaultValue: 20, tooltip: 'Idea pins published per month' },
    ],
  },
  {
    id: 'twitch',
    name: 'Twitch',
    icon: Twitch,
    iconColor: 'text-purple-500',
    accentColor: '#a855f7',
    gradient: 'from-purple-600 to-purple-800',
    description: 'Subscriptions, bits, and ads',
    inputs: [
      { id: 'subscribers', label: 'Subscribers', type: 'number', min: 0, max: 100000, defaultValue: 100, tooltip: 'Paid subscribers' },
      { id: 'avgViewers', label: 'Average Viewers', type: 'number', min: 0, max: 100000, defaultValue: 50, tooltip: 'Concurrent viewers' },
      { id: 'hoursStreamed', label: 'Hours Streamed / Month', type: 'slider', min: 1, max: 200, step: 1, defaultValue: 40, tooltip: 'Monthly streaming hours' },
    ],
  },
  {
    id: 'kick',
    name: 'Kick',
    icon: Gamepad2,
    iconColor: 'text-green-500',
    accentColor: '#22c55e',
    gradient: 'from-green-500 to-green-700',
    description: 'Subscriptions and platform bonuses',
    inputs: [
      { id: 'subscribers', label: 'Subscribers', type: 'number', min: 0, max: 100000, defaultValue: 50, tooltip: 'Paid subscribers' },
      { id: 'avgViewers', label: 'Average Viewers', type: 'number', min: 0, max: 100000, defaultValue: 30, tooltip: 'Concurrent viewers' },
    ],
  },
  {
    id: 'newsletter',
    name: 'Newsletter',
    icon: Mail,
    iconColor: 'text-emerald-500',
    accentColor: '#10b981',
    gradient: 'from-emerald-500 to-emerald-700',
    description: 'Paid subscriptions and sponsorships',
    inputs: [
      { id: 'subscribers', label: 'Total Subscribers', type: 'number', min: 0, max: 10000000, defaultValue: 5000, tooltip: 'Total email subscribers' },
      { id: 'paidPercent', label: 'Paid Subscriber %', type: 'slider', min: 0, max: 20, step: 0.5, defaultValue: 5, tooltip: 'Percentage who pay' },
      { id: 'monthlyPrice', label: 'Monthly Price ($)', type: 'slider', min: 1, max: 50, step: 1, defaultValue: 10, tooltip: 'Subscription price' },
    ],
  },
  {
    id: 'patreon',
    name: 'Patreon',
    icon: Heart,
    iconColor: 'text-orange-500',
    accentColor: '#f97316',
    gradient: 'from-orange-500 to-red-500',
    description: 'Memberships and exclusive content',
    inputs: [
      { id: 'patrons', label: 'Total Patrons', type: 'number', min: 0, max: 1000000, defaultValue: 100, tooltip: 'Number of paying patrons' },
      { id: 'avgPledge', label: 'Average Pledge ($)', type: 'slider', min: 1, max: 50, step: 1, defaultValue: 5, tooltip: 'Average monthly pledge amount' },
    ],
  },
  {
    id: 'kofi',
    name: 'Ko-fi',
    icon: Coffee,
    iconColor: 'text-cyan-500',
    accentColor: '#06b6d4',
    gradient: 'from-cyan-500 to-blue-500',
    description: 'Tips, memberships, and shop sales',
    inputs: [
      { id: 'supporters', label: 'Monthly Supporters', type: 'number', min: 0, max: 100000, defaultValue: 20, tooltip: 'One-time supporters per month' },
      { id: 'avgTip', label: 'Average Tip ($)', type: 'slider', min: 1, max: 25, step: 1, defaultValue: 5, tooltip: 'Average tip amount' },
      { id: 'members', label: 'Monthly Members', type: 'number', min: 0, max: 100000, defaultValue: 10, tooltip: 'Recurring membership subscribers' },
      { id: 'memberPrice', label: 'Membership Price ($)', type: 'slider', min: 1, max: 30, step: 1, defaultValue: 5, tooltip: 'Monthly membership price' },
    ],
  },
  {
    id: 'gumroad',
    name: 'Gumroad',
    icon: ShoppingBag,
    iconColor: 'text-pink-500',
    accentColor: '#ec4899',
    gradient: 'from-pink-500 to-rose-500',
    description: 'Digital products and courses',
    inputs: [
      { id: 'products', label: 'Products Sold / Month', type: 'number', min: 0, max: 10000, defaultValue: 50, tooltip: 'Units sold per month' },
      { id: 'avgPrice', label: 'Average Price ($)', type: 'slider', min: 1, max: 200, step: 5, defaultValue: 25, tooltip: 'Average product price' },
    ],
  },
  {
    id: 'podcast',
    name: 'Podcast',
    icon: Podcast,
    iconColor: 'text-violet-500',
    accentColor: '#8b5cf6',
    gradient: 'from-violet-500 to-purple-600',
    description: 'Spotify, Apple Podcasts, and sponsorships',
    inputs: [
      { id: 'downloads', label: 'Monthly Downloads', type: 'number', min: 0, max: 10000000, defaultValue: 10000, tooltip: 'Total monthly episode downloads' },
      { id: 'episodes', label: 'Episodes / Month', type: 'slider', min: 1, max: 30, step: 1, defaultValue: 4, tooltip: 'Episodes published per month' },
      { id: 'cpm', label: 'Sponsor CPM ($)', type: 'slider', min: 10, max: 50, step: 5, defaultValue: 25, tooltip: 'Cost per 1000 downloads for sponsors' },
    ],
  },
  {
    id: 'teachable',
    name: 'Courses',
    icon: GraduationCap,
    iconColor: 'text-amber-500',
    accentColor: '#f59e0b',
    gradient: 'from-amber-500 to-orange-500',
    description: 'Online courses via Teachable, Kajabi, etc.',
    inputs: [
      { id: 'students', label: 'Students / Month', type: 'number', min: 0, max: 10000, defaultValue: 20, tooltip: 'New enrollments per month' },
      { id: 'coursePrice', label: 'Course Price ($)', type: 'slider', min: 10, max: 500, step: 10, defaultValue: 100, tooltip: 'Average course price' },
      { id: 'platformFee', label: 'Platform Fee (%)', type: 'slider', min: 0, max: 20, step: 1, defaultValue: 5, tooltip: 'Platform transaction fee' },
    ],
  },
  {
    id: 'onlyfans',
    name: 'OnlyFans',
    icon: Users,
    iconColor: 'text-sky-500',
    accentColor: '#0ea5e9',
    gradient: 'from-sky-500 to-blue-500',
    description: 'Subscriptions, tips, and PPV content',
    inputs: [
      { id: 'subscribers', label: 'Subscribers', type: 'number', min: 0, max: 100000, defaultValue: 100, tooltip: 'Paying subscribers' },
      { id: 'subPrice', label: 'Subscription Price ($)', type: 'slider', min: 5, max: 50, step: 1, defaultValue: 10, tooltip: 'Monthly subscription price' },
      { id: 'tipsPercent', label: 'Tips (% of subs)', type: 'slider', min: 0, max: 100, step: 5, defaultValue: 20, tooltip: 'Additional tip revenue as % of sub revenue' },
    ],
  },
  {
    id: 'etsy',
    name: 'Etsy',
    icon: Store,
    iconColor: 'text-orange-600',
    accentColor: '#ea580c',
    gradient: 'from-orange-600 to-red-600',
    description: 'Handmade and digital product sales',
    inputs: [
      { id: 'orders', label: 'Orders / Month', type: 'number', min: 0, max: 10000, defaultValue: 30, tooltip: 'Total orders per month' },
      { id: 'avgOrder', label: 'Average Order ($)', type: 'slider', min: 5, max: 200, step: 5, defaultValue: 25, tooltip: 'Average order value' },
      { id: 'profitMargin', label: 'Profit Margin (%)', type: 'slider', min: 10, max: 90, step: 5, defaultValue: 50, tooltip: 'After materials and Etsy fees' },
    ],
  },
  {
    id: 'amazon',
    name: 'Amazon Influencer',
    icon: Package,
    iconColor: 'text-yellow-500',
    accentColor: '#eab308',
    gradient: 'from-yellow-500 to-amber-600',
    description: 'Storefront commissions and bounties',
    inputs: [
      { id: 'pageViews', label: 'Storefront Views / Month', type: 'number', min: 0, max: 1000000, defaultValue: 5000, tooltip: 'Monthly storefront page views' },
      { id: 'conversionRate', label: 'Conversion Rate (%)', type: 'slider', min: 1, max: 15, step: 0.5, defaultValue: 3, tooltip: 'Visitors who purchase' },
      { id: 'avgCommission', label: 'Avg Commission ($)', type: 'slider', min: 1, max: 20, step: 1, defaultValue: 4, tooltip: 'Average commission per sale' },
    ],
  },
  {
    id: 'fansly',
    name: 'Fansly',
    icon: Sparkles,
    iconColor: 'text-blue-400',
    accentColor: '#60a5fa',
    gradient: 'from-blue-400 to-cyan-500',
    description: 'Subscriptions, tips, and PPV content',
    inputs: [
      { id: 'subscribers', label: 'Subscribers', type: 'number', min: 0, max: 100000, defaultValue: 100, tooltip: 'Paying subscribers' },
      { id: 'subPrice', label: 'Subscription Price ($)', type: 'slider', min: 5, max: 50, step: 1, defaultValue: 10, tooltip: 'Monthly subscription price' },
      { id: 'tipsPercent', label: 'Tips (% of subs)', type: 'slider', min: 0, max: 100, step: 5, defaultValue: 20, tooltip: 'Additional tip revenue as % of sub revenue' },
    ],
  },
  {
    id: 'fanvue',
    name: 'Fanvue',
    icon: Send,
    iconColor: 'text-green-400',
    accentColor: '#00DC6E',
    gradient: 'from-green-400 to-green-600',
    description: 'Subscriptions, tips, and PPV content',
    inputs: [
      { id: 'subscribers', label: 'Subscribers', type: 'number', min: 0, max: 100000, defaultValue: 100, tooltip: 'Paying subscribers' },
      { id: 'subPrice', label: 'Subscription Price ($)', type: 'slider', min: 5, max: 50, step: 1, defaultValue: 10, tooltip: 'Monthly subscription price' },
      { id: 'tipsPercent', label: 'Tips (% of subs)', type: 'slider', min: 0, max: 100, step: 5, defaultValue: 20, tooltip: 'Additional tip revenue as % of sub revenue' },
    ],
  },
  {
    id: 'threads',
    name: 'Threads',
    icon: AtSign,
    iconColor: 'text-zinc-300',
    accentColor: '#d4d4d8',
    gradient: 'from-zinc-400 to-zinc-600',
    description: 'Brand deals and sponsorships',
    inputs: [
      { id: 'followers', label: 'Followers', type: 'number', min: 0, max: 10000000, defaultValue: 10000, tooltip: 'Total followers' },
      { id: 'avgLikes', label: 'Avg Likes per Post', type: 'number', min: 0, max: 1000000, defaultValue: 500, tooltip: 'Average likes per post' },
      { id: 'postsPerMonth', label: 'Posts / Month', type: 'slider', min: 1, max: 100, step: 1, defaultValue: 20, tooltip: 'Posts per month' },
    ],
  },
  {
    id: 'discord',
    name: 'Discord',
    icon: MessageCircle,
    iconColor: 'text-indigo-400',
    accentColor: '#818cf8',
    gradient: 'from-indigo-500 to-purple-600',
    description: 'Server subscriptions and roles',
    inputs: [
      { id: 'members', label: 'Paying Members', type: 'number', min: 0, max: 100000, defaultValue: 50, tooltip: 'Members with paid roles/subscriptions' },
      { id: 'avgPrice', label: 'Avg Subscription ($)', type: 'slider', min: 1, max: 30, step: 1, defaultValue: 5, tooltip: 'Average monthly subscription price' },
    ],
  },
  {
    id: 'rumble',
    name: 'Rumble',
    icon: Play,
    iconColor: 'text-green-400',
    accentColor: '#4ade80',
    gradient: 'from-green-400 to-emerald-600',
    description: 'Ad revenue and Rumble Rants',
    inputs: [
      { id: 'monthlyViews', label: 'Monthly Views', type: 'number', min: 0, max: 100000000, defaultValue: 50000, tooltip: 'Total monthly video views' },
      { id: 'cpm', label: 'CPM ($)', type: 'slider', min: 1, max: 15, step: 0.5, defaultValue: 3, tooltip: 'Revenue per 1000 views' },
      { id: 'rants', label: 'Rant Supporters', type: 'number', min: 0, max: 10000, defaultValue: 10, tooltip: 'Monthly Rumble Rant supporters' },
    ],
  },
  {
    id: 'substack',
    name: 'Substack',
    icon: BookOpen,
    iconColor: 'text-orange-400',
    accentColor: '#fb923c',
    gradient: 'from-orange-400 to-orange-600',
    description: 'Paid newsletter subscriptions',
    inputs: [
      { id: 'freeSubscribers', label: 'Free Subscribers', type: 'number', min: 0, max: 1000000, defaultValue: 5000, tooltip: 'Total free subscribers' },
      { id: 'paidPercent', label: 'Paid Conversion (%)', type: 'slider', min: 1, max: 20, step: 0.5, defaultValue: 5, tooltip: 'Percentage who pay' },
      { id: 'monthlyPrice', label: 'Monthly Price ($)', type: 'slider', min: 3, max: 30, step: 1, defaultValue: 10, tooltip: 'Monthly subscription price' },
    ],
  },
]
