import { useState } from 'react'
import jsPDF from 'jspdf'
import { X, FileText, FileSpreadsheet, Check, Crown } from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { platforms } from '@/platforms/registry'
import { usePro } from '@/contexts/ProContext'

interface ExportResultsProps {
  platformId: string
  inputValues: Record<string, number>
  results: {
    monthlyRevenue: number
    yearlyRevenue: number
    engagementRate?: number
  }
  theme: 'dark' | 'light'
  onClose: () => void
}

export function ExportResults({
  platformId,
  inputValues,
  results,
  theme,
  onClose,
}: ExportResultsProps) {
  const [exportingPDF, setExportingPDF] = useState(false)
  const [exportingCSV, setExportingCSV] = useState(false)
  const [pdfSuccess, setPdfSuccess] = useState(false)
  const [csvSuccess, setCsvSuccess] = useState(false)

  const { canUseFeature, triggerUpgrade, isPro } = usePro()
  const platform = platforms.find(p => p.id === platformId)

  const formatCurrency = (num: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    }).format(num)
  }

  const formatNumber = (num: number) => {
    return new Intl.NumberFormat('en-US').format(num)
  }

  const getInputsData = () => {
    if (!platform) return []
    return platform.inputs.map(input => ({
      label: input.label,
      value: inputValues[input.id] ?? input.defaultValue,
      id: input.id,
    }))
  }

  const handleExportPDF = async () => {
    if (!canUseFeature('export-pdf')) {
      triggerUpgrade('export-pdf')
      return
    }

    if (!platform) return
    setExportingPDF(true)
    setPdfSuccess(false)

    try {
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      })

      const pageWidth = pdf.internal.pageSize.getWidth()
      let yPos = 20

      // Title
      pdf.setFontSize(24)
      pdf.setTextColor(88, 28, 135) // Purple
      pdf.text(`${platform.name} Revenue Report`, pageWidth / 2, yPos, { align: 'center' })
      yPos += 15

      // Subtitle
      pdf.setFontSize(12)
      pdf.setTextColor(100, 100, 100)
      pdf.text(`Generated by SocialStacks on ${new Date().toLocaleDateString()}`, pageWidth / 2, yPos, { align: 'center' })
      yPos += 20

      // Revenue Summary Box
      pdf.setFillColor(245, 245, 245)
      pdf.roundedRect(15, yPos, pageWidth - 30, 40, 3, 3, 'F')

      pdf.setFontSize(14)
      pdf.setTextColor(50, 50, 50)
      pdf.text('Revenue Summary', 20, yPos + 10)

      pdf.setFontSize(20)
      pdf.setTextColor(34, 197, 94) // Green
      pdf.text(`${formatCurrency(results.monthlyRevenue)}/month`, 20, yPos + 25)

      pdf.setFontSize(14)
      pdf.setTextColor(100, 100, 100)
      pdf.text(`${formatCurrency(results.yearlyRevenue)}/year`, 20, yPos + 35)
      yPos += 55

      // Input Metrics Section
      pdf.setFontSize(16)
      pdf.setTextColor(50, 50, 50)
      pdf.text('Your Metrics', 20, yPos)
      yPos += 10

      pdf.setFontSize(11)
      const inputs = getInputsData()
      inputs.forEach((input) => {
        pdf.setTextColor(100, 100, 100)
        pdf.text(`${input.label}:`, 20, yPos)
        pdf.setTextColor(50, 50, 50)
        pdf.text(formatNumber(input.value), 100, yPos)
        yPos += 8
      })
      yPos += 10

      // Projections Section
      pdf.setFontSize(16)
      pdf.setTextColor(50, 50, 50)
      pdf.text('Earnings Projections', 20, yPos)
      yPos += 10

      pdf.setFontSize(11)
      const projections = [
        { label: 'Daily', value: results.monthlyRevenue / 30 },
        { label: 'Weekly', value: results.monthlyRevenue / 4.33 },
        { label: 'Monthly', value: results.monthlyRevenue },
        { label: 'Quarterly', value: results.monthlyRevenue * 3 },
        { label: 'Yearly', value: results.yearlyRevenue },
      ]

      projections.forEach((proj) => {
        pdf.setTextColor(100, 100, 100)
        pdf.text(`${proj.label}:`, 20, yPos)
        pdf.setTextColor(34, 197, 94)
        pdf.text(formatCurrency(proj.value), 100, yPos)
        yPos += 8
      })
      yPos += 15

      // Footer
      pdf.setFontSize(10)
      pdf.setTextColor(150, 150, 150)
      pdf.text('This is an estimate based on industry averages. Actual earnings may vary.', pageWidth / 2, 280, { align: 'center' })
      pdf.text('creator-calculator.vercel.app', pageWidth / 2, 287, { align: 'center' })

      // Save
      pdf.save(`${platform.name.toLowerCase()}-revenue-report.pdf`)
      setPdfSuccess(true)
      setTimeout(() => setPdfSuccess(false), 3000)
    } catch (error) {
      console.error('PDF export failed:', error)
    } finally {
      setExportingPDF(false)
    }
  }

  const handleExportCSV = () => {
    if (!canUseFeature('export-csv')) {
      triggerUpgrade('export-csv')
      return
    }

    if (!platform) return
    setExportingCSV(true)
    setCsvSuccess(false)

    try {
      const inputs = getInputsData()

      // Build CSV content
      const rows: string[][] = [
        ['SocialStacks - Revenue Report'],
        [`Platform: ${platform.name}`],
        [`Generated: ${new Date().toLocaleString()}`],
        [],
        ['--- YOUR METRICS ---'],
        ['Metric', 'Value'],
      ]

      inputs.forEach(input => {
        rows.push([input.label, input.value.toString()])
      })

      rows.push([])
      rows.push(['--- REVENUE ESTIMATES ---'])
      rows.push(['Period', 'Amount (USD)'])
      rows.push(['Daily', (results.monthlyRevenue / 30).toFixed(2)])
      rows.push(['Weekly', (results.monthlyRevenue / 4.33).toFixed(2)])
      rows.push(['Monthly', results.monthlyRevenue.toFixed(2)])
      rows.push(['Quarterly', (results.monthlyRevenue * 3).toFixed(2)])
      rows.push(['Yearly', results.yearlyRevenue.toFixed(2)])

      if (results.engagementRate) {
        rows.push([])
        rows.push(['Engagement Rate (%)', results.engagementRate.toFixed(2)])
      }

      rows.push([])
      rows.push(['Note: These are estimates based on industry averages. Actual earnings may vary.'])

      const csvContent = rows.map(row => row.join(',')).join('\n')

      // Download
      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
      const link = document.createElement('a')
      link.href = URL.createObjectURL(blob)
      link.download = `${platform.name.toLowerCase()}-revenue-report.csv`
      link.click()
      URL.revokeObjectURL(link.href)

      setCsvSuccess(true)
      setTimeout(() => setCsvSuccess(false), 3000)
    } catch (error) {
      console.error('CSV export failed:', error)
    } finally {
      setExportingCSV(false)
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80">
      <div className={`relative max-w-md w-full mx-4 rounded-xl p-6 ${theme === 'dark' ? 'bg-zinc-900' : 'bg-white'}`}>
        <button
          onClick={onClose}
          className={`absolute top-4 right-4 p-2 rounded-full transition-colors ${theme === 'dark' ? 'hover:bg-zinc-800 text-zinc-400 hover:text-white' : 'hover:bg-gray-100 text-gray-500 hover:text-gray-900'}`}
        >
          <X className="w-5 h-5" />
        </button>

        <div className="mb-6">
          <h2 className={`text-xl font-bold ${theme === 'dark' ? 'text-white' : 'text-zinc-900'}`}>
            Export Results
          </h2>
          <p className={`text-sm mt-1 ${theme === 'dark' ? 'text-zinc-400' : 'text-zinc-600'}`}>
            Download your {platform?.name} revenue report
          </p>
        </div>

        {/* Revenue Preview */}
        <Card className={`mb-6 ${theme === 'dark' ? 'bg-zinc-800 border-zinc-700' : 'bg-gray-50 border-gray-200'}`}>
          <CardContent className="pt-4">
            <p className={`text-sm ${theme === 'dark' ? 'text-zinc-400' : 'text-zinc-600'}`}>Estimated Monthly Revenue</p>
            <p className="text-3xl font-bold text-emerald-500">{formatCurrency(results.monthlyRevenue)}</p>
            <p className={`text-sm mt-1 ${theme === 'dark' ? 'text-zinc-500' : 'text-zinc-500'}`}>
              {formatCurrency(results.yearlyRevenue)}/year
            </p>
          </CardContent>
        </Card>

        {/* Export Buttons */}
        <div className="space-y-3">
          <Button
            onClick={handleExportPDF}
            disabled={exportingPDF}
            className="w-full flex items-center justify-center gap-2 bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 text-white py-6"
          >
            {pdfSuccess ? (
              <>
                <Check className="w-5 h-5" />
                Downloaded!
              </>
            ) : exportingPDF ? (
              <>
                <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" />
                Generating PDF...
              </>
            ) : (
              <>
                <FileText className="w-5 h-5" />
                Export as PDF
                {!isPro && <Crown className="w-4 h-4 ml-2 text-yellow-400" />}
              </>
            )}
          </Button>

          <Button
            onClick={handleExportCSV}
            disabled={exportingCSV}
            variant="outline"
            className={`w-full flex items-center justify-center gap-2 py-6 ${theme === 'dark' ? 'border-zinc-700 hover:bg-zinc-800' : 'border-gray-300 hover:bg-gray-100'}`}
          >
            {csvSuccess ? (
              <>
                <Check className="w-5 h-5 text-emerald-500" />
                <span className="text-emerald-500">Downloaded!</span>
              </>
            ) : exportingCSV ? (
              <>
                <div className="w-5 h-5 border-2 border-current border-t-transparent rounded-full animate-spin" />
                Generating CSV...
              </>
            ) : (
              <>
                <FileSpreadsheet className="w-5 h-5" />
                Export as CSV
                {!isPro && <Crown className="w-4 h-4 ml-2 text-yellow-400" />}
              </>
            )}
          </Button>
        </div>

        <p className={`text-xs text-center mt-4 ${theme === 'dark' ? 'text-zinc-500' : 'text-zinc-400'}`}>
          Exports include your metrics and revenue projections
        </p>
      </div>
    </div>
  )
}
